from enum import StrEnum


class CompanyAdminApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    PENDING_FINAL_APPROVAL = "PENDING_FINAL_APPROVAL"
    APPROVED = "APPROVED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    EXPIRED = "EXPIRED"
